### PR TITLE
Add button test connection in global configuration

### PR DESCRIPTION
**Pull request by mat1e**
Link to #150

Here is the Test Connection button part.

### CODE REVIEW

File: src/main/java/jenkinsci/plugins/influxdb/models/Target.java [hunk 1]
```diff
@@ -181,5 +199,59 @@ public FormValidation doCheckUrl(@QueryParameter String value) {
...
+                    influxDB = InfluxDBClientFactory.create(options.build());
+
+                } else {
+                    influxDB = credentials == null
+                            ? InfluxDBClientFactory.createV1(url, "", "".toCharArray(), database, retentionPolicy)
+                            : InfluxDBClientFactory.createV1(url, credentials.getUsername(),
+                                    credentials.getPassword().getPlainText().toCharArray(), database, retentionPolicy);
+                }
+
+                Bucket bucket = influxDB.getBucketsApi().findBucketByName(database);
```
Comment (asimell) [inline src/main/java/jenkinsci/plugins/influxdb/models/Target.java]: Does this work with InfluxDB 1.8 targets? I get a long error stack trace every time I try to test the connection of a 1.8 target.

Comment (asimell) [reply src/main/java/jenkinsci/plugins/influxdb/models/Target.java]: Also 2.x validation fails with
```
java.lang.NoSuchMethodError: 'com.google.gson.stream.JsonReader com.google.gson.Gson.newJsonReader(java.io.Reader)'
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:38)
	at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	at com.influxdb.internal.AbstractRestClient.execute(AbstractRestClient.java:78)
	at com.influxdb.client.internal.BucketsApiImpl.findBucketByName(BucketsApiImpl.java:93)
	at jenkinsci.plugins.influxdb.models.Target$DescriptorImpl.doVerifyConnection(Target.java:246)
	...
```

Comment (mat1e) [reply src/main/java/jenkinsci/plugins/influxdb/models/Target.java]: Sorry, I don't have many influxDB versions... I test only on my own (I work with influxDB 2.2.0). 
For `NoSuchMethodError`, I'm using the same client (OkHttp) used by the entire plugin, and instanciate it with `InfluxDBClientFactory`. So if it fails with this error here, you should have this error elsewhere...

File: src/main/java/jenkinsci/plugins/influxdb/models/Target.java [hunk 2]
```diff
@@ -181,5 +199,59 @@ public FormValidation doCheckUrl(@QueryParameter String value) {
...
+            InfluxDBClient influxDB = null;
+            doCheckUrl(url);
+            doCheckDatabase(database);
+            try {
+                Jenkins.get().checkPermission(Jenkins.ADMINISTER);
+
+                List<StandardUsernamePasswordCredentials> lookupCredentials = CredentialsProvider.lookupCredentials(
+                        StandardUsernamePasswordCredentials.class,
+                        context,
+                        ACL.SYSTEM,
```
Comment (asimell) [inline src/main/java/jenkinsci/plugins/influxdb/models/Target.java:217]: [ACL.SYSTEM is deprecated](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#SYSTEM) and `ACL.SYSTEM2` should be used instead.

File: src/main/java/jenkinsci/plugins/influxdb/models/Target.java [hunk 3]
```diff
@@ -181,5 +199,59 @@ public FormValidation doCheckUrl(@QueryParameter String value) {
...
+                if (organization != null && !organization.trim().isEmpty()) {
+                    InfluxDBClientOptions.Builder options = InfluxDBClientOptions.builder().url(url).org(organization).bucket(database);
+
+                    if (credentials != null) { // basic auth
+                        options.authenticate(credentials.getUsername(), credentials.getPassword().getPlainText().toCharArray());
+                    } else { // token auth
+                        List<StringCredentials> lookupTokenCredentials = CredentialsProvider.lookupCredentials(//
+                                StringCredentials.class,//
+                                context,//
+                                ACL.SYSTEM,//
```
Comment (asimell) [inline src/main/java/jenkinsci/plugins/influxdb/models/Target.java]: [ACL.SYSTEM is deprecated](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#SYSTEM) and `ACL.SYSTEM2` should be used instead.

File: src/main/java/jenkinsci/plugins/influxdb/models/Target.java [hunk 4]
```diff
@@ -181,5 +199,59 @@ public FormValidation doCheckUrl(@QueryParameter String value) {
...
+                                URIRequirementBuilder.fromUri(url).build());//
```
Comment (asimell) [inline src/main/java/jenkinsci/plugins/influxdb/models/Target.java]: Please remove unnecessary empty comment slashes.

File: src/main/java/jenkinsci/plugins/influxdb/models/Target.java (hunk 1 above)
Comment (asimell) [reply src/main/java/jenkinsci/plugins/influxdb/models/Target.java]: Yes, but as you can see `findBucketByName` uses `retrofit2.OkHttpCall` instead of `okhttp3.OkHttpClient` (as used by the plugin elsewhere). The issue is with that one particular call `Bucket bucket = influxDB.getBucketsApi().findBucketByName(database);` which is causing this issue and as the plugin also needs to support InfluxDB 1.8, it's not succeeding with that.

Comment (mat1e) [reply src/main/java/jenkinsci/plugins/influxdb/models/Target.java]: I did an update to only call a "ping", but I don't understand the error you get because elsewhere in the plugin I found use of retrofit2 :

```
    @Nonnull
    @Override
    public WriteApiBlocking getWriteApiBlocking() {
        return new WriteApiBlockingImpl(retrofit.create(WriteService.class), options);
    }
```

This is the api used to write point...
I think there is a dependency conflict somewhere because the plugin is using his own okhttp instead of [okhttp-api](https://plugins.jenkins.io/okhttp-api/)

File: src/main/java/jenkinsci/plugins/influxdb/models/Target.java (hunk 2 above)
Comment (mat1e) [reply src/main/java/jenkinsci/plugins/influxdb/models/Target.java:217]: [ACL.SYSTEM](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#SYSTEM) is already used in your plugin, I suggest to do the modification in another feature.

File: src/main/java/jenkinsci/plugins/influxdb/models/Target.java (hunk 3 above)
Comment (mat1e) [reply src/main/java/jenkinsci/plugins/influxdb/models/Target.java]: [ACL.SYSTEM](https://javadoc.jenkins-ci.org/hudson/security/ACL.html#SYSTEM) is already used in your plugin, I suggest to do the modification in another feature.

File: src/main/java/jenkinsci/plugins/influxdb/models/Target.java (hunk 1 above)
Comment (asimell) [reply src/main/java/jenkinsci/plugins/influxdb/models/Target.java]: Thank you, now both InfluxDB 1.8 and 2.2 targets work without any error traces in logs either.

**Review by asimell — APPROVED** [review]
LGTM
